name: Deploy to itch.io

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Godot
      uses: josephbmanley/setup-godot@v1
      with:
        godot-version: 4.3.0  # Update to your version of Godot

    - name: Export project
      run: godot --export-release "HTML5" "build/index.html"

    - name: Install Butler
      run: |
        curl -L https://broth.itch.ovh/butler/linux-amd64/latest/archive/default | tar xz
        sudo mv butler /usr/local/bin/

    - name: Deploy to itch.io
      env:
        BUTLER_CREDENTIALS: ${{ secrets.ITCHIOKEY }}
      run: |
        butler push build/ several.herr/atomic-robot:html5
