name: Deploy to itch.io

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip -O godot.zip
        unzip godot.zip -d godot
        mv godot/Godot_v4.3-stable_linux.x86_64 /usr/local/bin/godot
        chmod +x /usr/local/bin/godot

    - name: Download Godot Export Templates
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz -O templates.zip
        mkdir -p ~/.local/share/godot/export_templates/4.3.stable
        unzip templates.zip -d ~/.local/share/godot/export_templates/4.3.stable
        mv ~/.local/share/godot/export_templates/4.3.stable/templates/* ~/.local/share/godot/export_templates/4.3.stable/
        rmdir ~/.local/share/godot/export_templates/4.3.stable/templates

    - name: List Export Template Files
      run: ls ~/.local/share/godot/export_templates/4.3.stable/

    - name: Export project
      run: godot --headless --export-release "Web" "bin/index.html"


    - name: Install Butler
      run: |
        curl -L https://broth.itch.ovh/butler/linux-amd64/15.21.0/archive-default | tar xz
        sudo mv butler /usr/local/bin/

    - name: Deploy to itch.io
      env:
        BUTLER_CREDENTIALS: ${{ secrets.ITCHIOKEY }}
      run: |
        butler push build/ several.herr/atomic-robot:html5
