name: Deploy to itch.io

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Godot
      run: |
        wget https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_linux.x86_64.zip -O godot.zip
        unzip godot.zip -d godot
        mv godot/Godot.zip /usr/local/bin/godot
        chmod +x /usr/local/bin/godot

    - name: Export project
      run: godot --export-release "HTML5" "build/index.html"


    - name: Install Butler
      run: |
        curl -L https://broth.itch.ovh/butler/linux-amd64/latest/archive/default | tar xz
        sudo mv butler /usr/local/bin/

    - name: Deploy to itch.io
      env:
        BUTLER_CREDENTIALS: ${{ secrets.ITCHIOKEY }}
      run: |
        butler push build/ several.herr/atomic-robot:html5
